name: valklegs
m_name: <color=#D4AF37>valklegs</color>
AppendToolTip: \n<color=#696969>Valkyrie's Grace</color>\n<color=#888888>Cannot be crafted — bestowed by Fallen Valkyrie.\n<i>(~1% drop chance)</i></color>

