name: samurailegs
m_name: <color=#D4AF37>samurailegs</color>
AppendToolTip: \n<color=#696969>Samurai Regalia</color>\n<color=#888888>Cannot be crafted — earned from Plains champions.\n<i>(~1% combined Plains elite drops)</i></color>

