name: KnifeViper_TW
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 2
maxStationLevelCap: 7
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []`n- Bronze:11:2
- Bronze:22:3
- Bronze:33:4
- Iron:11:5
- Iron:22:6
- Iron:33:7
- Iron:44:8
- Silver:11:9
- Silver:22:10
- Silver:33:11
- Silver:44:12
- HardAntler:6:2
- HardAntler:12:3
- HardAntler:18:4
- Root:6:5
- Root:12:6
- Root:18:7
- Root:24:8
- WolfClaw:6:9
- WolfClaw:12:10
- WolfClaw:18:11
- WolfClaw:24:12
- SurtlingCore:2:2
- SurtlingCore:4:3
- SurtlingCore:6:4
- WitheredBone:2:5
- WitheredBone:4:6
- WitheredBone:6:7
- WitheredBone:8:8
- WolfHairBundle:2:9
- WolfHairBundle:4:10
- WolfHairBundle:6:11
- WolfHairBundle:8:12
- TrophyAsmodeus_TW:1:2
- TrophyAsmodeus_TW:1:3
- TrophyAsmodeus_TW:1:4
- TrophyAbomination:1:5
- TrophyAbomination:1:6
- TrophyAbomination:1:7
- TrophyAbomination:1:8
- TrophyFenring:1:9
- TrophyFenring:1:10
- TrophyFenring:1:11
- TrophyFenring:1:12
reqs:
- Bronze:22:11:True
- HardAntler:12:6:True
- SurtlingCore:4:2:True
- TrophyAsmodeus_TW:1:1:True

