name: CrossbowEikthyr_TW
clonePrefabName: 
craftingStation: FletcherTable_TW
minStationLevel: 1
maxStationLevelCap: 5
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs:
- RoundLog:15:2
- RoundLog:30:3
- RoundLog:45:4
- Bronze:15:5
- Bronze:30:6
- Bronze:45:7
- Bronze:60:8
- Iron:15:9
- Iron:30:10
- Iron:45:11
- Iron:60:12
- HardAntler:8:2
- HardAntler:16:3
- HardAntler:24:4
- TrollHide:8:5
- TrollHide:16:6
- TrollHide:24:7
- TrollHide:32:8
- RottenPelt_TW:8:9
- RottenPelt_TW:16:10
- RottenPelt_TW:24:11
- RottenPelt_TW:32:12
- DeerHide:8:2
- DeerHide:16:3
- DeerHide:24:4
- BronzeNails:8:5
- BronzeNails:16:6
- BronzeNails:24:7
- BronzeNails:32:8
- IronNails:8:9
- IronNails:16:10
- IronNails:24:11
- IronNails:32:12
- TrophyEikthyr:1:2
- TrophyEikthyr:1:3
- TrophyEikthyr:1:4
- TrophyFrostTroll:1:5
- TrophyFrostTroll:1:6
- TrophyFrostTroll:1:7
- TrophyFrostTroll:1:8
- TrophyAbomination:1:9
- TrophyAbomination:1:10
- TrophyAbomination:1:11
- TrophyAbomination:1:12
reqs:
- RoundLog:30:15:True
- HardAntler:16:8:True
- DeerHide:16:8:True
- TrophyEikthyr:1:1:True

