name: StaffMistlands_TW
clonePrefabName: StaffMistlands_TW
craftingStation: $piece_wizardtable_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: $piece_wizardtable_TW
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Staffbase_Mistlands_TW:1:1:True
- Staffcore_Mistlands_TW:1:1:True
- ArcaneScroll_Mistlands_TW:1:1:True
- TrophyGjall:1:1:True
