name: StaffSkrymir_TW
clonePrefabName: StaffSkrymir_TW
craftingStation: $piece_wizardtable_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: $piece_wizardtable_TW
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- TyraniumBar_TW:30:1:True
- RuneRage_TW:18:1:True
- YmirIdol_TW:6:1:True
- TrophyJotunnShaman_TW:1:1:True
