name: ScholarFireStaff
clonePrefabName: ScholarFireStaff
craftingStation: $piece_wizardtable_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: $piece_wizardtable_TW
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- GreydwarfEye:50:1:True
- Bronze:10:1:True
- Ruby:5:1:True
- FineWood:20:1:True
