name: StaffBlackforest_TW
clonePrefabName: StaffBlackforest_TW
craftingStation: $piece_wizardtable_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: $piece_wizardtable_TW
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Staffbase_BlackForest_TW:1:1:True
- Staffcore_BlackForest_TW:1:1:True
- ArcaneScroll_BlackForest_TW:1:1:True
