name: StaffSkrymir_TW
m_name: "<color=#D4AF37>$staff_skrymir_TW</color>"
AppendToolTip: "\n<color=#696969>Skrymir's Edict</color>\n<color=#888888>Cannot be crafted — bound by the glacial giants.\n<i>(5% drop chance from Jotunn)</i></color>"

