name: Recipe_FrostGodJotnarCape
clonePrefabName: NO
craftingStation: $piece_blackforge
minStationLevel: 2
maxStationLevelCap: 
repairStation: $piece_blackforge
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- shawfrostlegs:1:1:True
- shawfrostchest:1:1:True
- shawfrosthelm:1:1:True
- DragonTear:1:5:True
