name: trollchest_Recipe_Forge
clonePrefabName: NO
craftingStation: $piece_forge
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Bronze:8:5:True
- BoneFragments:5:3:True
- TrophyFrostTroll:1:0:True
