name: bpchest_Recipe_Forge
clonePrefabName: NO
craftingStation: $piece_forge
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- BlackMetal:20:5:True
- Silver:5:3:True
- JuteRed:5:0:True
