name: BMR_PaperLow_Recipe_Custom
clonePrefabName: NO
craftingStation: $bmr_spell_table
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 50
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Wood:10:0:True
- Resin:2:0:True
