name: Odins_Dragon_Staff_Recipe_Workbench
clonePrefabName: NO
craftingStation: $piece_workbench
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Odins_Alchemy_Wand:1:0:True
- ElderBark:40:20:True
- BlackMetal:40:20:True
- SurtlingCore:1:0:True
