name: Mob_chunks_Recipe_Cauldron
clonePrefabName: NO
craftingStation: $piece_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: true
upgrade_reqs: []
reqs:
- TrophyBoar:2:0:True
- TrophyNeck:2:0:True
- TrophyDeer:2:0:True
- TrophyFox_TW:2:0:True
- TrophySheep_TW:2:0:True
- TrophyFrostTroll:1:0:True
- TrophyRazorback_TW:2:0:True
- TrophyBlackBear_TW:2:0:True
- TrophyGreydwarfBrute:2:0:True
- TrophyGreydwarfShaman:2:0:True
- TrophyCrawler_TW:2:0:True
- TrophyRottingElk_TW:2:0:True
- TrophyBlob:2:0:True
- TrophySurtling:2:0:True
- TrophyGreydwarf:2:0:True
- TrophyDraugr:2:0:True
- TrophyLeech:2:0:True
- TrophyWraith:1:0:True
- TrophyDraugrElite:1:0:True
- TrophyAbomination:1:0:True
- TrophySkeleton:2:0:True
- TrophySkeletonPoison:1:0:True
- TrophySerpent:1:0:True
- TrophyWolf:2:0:True
- TrophyUlv:2:0:True
- TrophyCultist:1:0:True
- TrophyFenring:1:0:True
- TrophyObsidianGolem_TW:1:0:True
- TrophySGolem:1:0:True
- TrophyGrizzlyBear_TW:2:0:True
- TrophyProwler_TW:1:0:True
- TrophyShark_TW:2:0:True
- TrophyLox:1:0:True
- TrophyDeathsquito:2:0:True
- TrophyGoblin:2:0:True
- TrophyGrowth:2:0:True
- TrophyGoblinBrute:1:0:True
- TrophyGoblinShaman:1:0:True
- TrophyHare:2:0:True
- TrophySeeker:2:0:True
- TrophyTick:2:0:True
- TrophyDvergr:2:0:True
- TrophySeekerBrute:1:0:True
- TrophyGjall:1:0:True
- TrophyAsksvin:1:0:True
- TrophyBonemawSerpent:1:0:True
- TrophyCharredArcher:2:0:True
- TrophyCharredMage:2:0:True
- TrophyCharredMelee:2:0:True
- TrophyFallenValkyrie:1:0:True
- TrophyMorgen:1:0:True
- TrophyVolture:2:0:True
- TrophySkeletonHildir:1:0:True
- TrophyCultist_Hildir:1:0:True
- TrophyGoblinBruteBrosBrute:1:0:True
- TrophyGoblinBruteBrosShaman:1:0:True
- TrophyJotunnBrute_TW:1:0:True
- TrophyJotunnJuggernaut_TW:1:0:True
- TrophyJotunnShaman_TW:2:0:True
- TrophyJotunnBladefist_TW:2:0:True
- TrophyArcticBear_TW:2:0:True
- TrophyArcticMammoth_TW:1:0:True
- TrophyStormFenring_TW:1:0:True
- TrophyStormCultist_TW:1:0:True
- TrophyArcticWolf_TW:2:0:True
- TrophyArcticGolem_TW:1:0:True
- TrophyArcticSerpent_TW:1:0:True
- TrophyGorr_TW:1:0:True
- TrophySythrak_TW:1:0:True
- TrophySurtrBrute_TW:1:0:True
- TrophySurtrLegionnaire_TW:1:0:True
- TrophySurtrHound_TW:2:0:True
- TrophySurtrImp_TW:2:0:True
- TrophySurtrDrake_TW:2:0:True
- TrophySurtrSeer_TW:2:0:True
- TrophySurtrWarbringer_TW:1:0:True
- TrophyDaggerFang_TW:1:0:True
- TrophyBrutalis_TW:1:0:True
