name: Recipe_SOnionSoup_RtD
clonePrefabName: NO
craftingStation: $piece_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- WolfMeat:2:0:True
- Onion:6:0:True
- FreezeGland:2:0:True
