name: Recipe_DhakharShield
clonePrefabName: NO
craftingStation: $piece_blackforge
minStationLevel: 2
maxStationLevelCap: 
repairStation: $piece_blackforge
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Arcanium:1:1:True
- HasRefiner_Item:1:1:True
- FlametalNew:1:1:True
