name: bearlegs2_Recipe_BlackForge
clonePrefabName: NO
craftingStation: $piece_blackforge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- bearlegs:1:0:True
- BlackMarble:20:10:True
- JuteBlue:10:5:True
