name: Recipe_SageFireStaff
clonePrefabName: NO
craftingStation: $piece_forge
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- DragonTear:10:5:True
- Silver:60:10:True
- Crystal:30:10:True
- ElderBark:20:10:True
