name: CrossbowEikthyr_TW
clonePrefabName: 
craftingStation: $piece_fletchertable_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- RoundLog:0:15:True
- RoundLog:0:30:True
- RoundLog:0:45:True
- Bronze:0:15:True
- Bronze:0:30:True
- Bronze:0:45:True
- Bronze:0:60:True
- Iron:0:15:True
- Iron:0:30:True
- Iron:0:45:True
- Iron:0:60:True
- HardAntler:0:8:True
- HardAntler:0:16:True
- HardAntler:0:24:True
- TrollHide:0:8:True
- TrollHide:0:16:True
- TrollHide:0:24:True
- TrollHide:0:32:True
- RottenPelt_TW:0:8:True
- RottenPelt_TW:0:16:True
- RottenPelt_TW:0:24:True
- RottenPelt_TW:0:32:True
- DeerHide:0:8:True
- DeerHide:0:16:True
- DeerHide:0:24:True
- BronzeNails:0:8:True
- BronzeNails:0:16:True
- BronzeNails:0:24:True
- BronzeNails:0:32:True
- IronNails:0:8:True
- IronNails:0:16:True
- IronNails:0:24:True
- IronNails:0:32:True
- TrophyEikthyr:0:1:True
- TrophyEikthyr:0:1:True
- TrophyEikthyr:0:1:True
- TrophyFrostTroll:0:1:True
- TrophyFrostTroll:0:1:True
- TrophyFrostTroll:0:1:True
- TrophyFrostTroll:0:1:True
- TrophyAbomination:0:1:True
- TrophyAbomination:0:1:True
- TrophyAbomination:0:1:True
- TrophyAbomination:0:1:True
