name: Recipe_MountainMageLegs_RtD
clonePrefabName: NO
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Obsidian:10:2:True
- WolfPelt:10:2:True
- Crystal:5:2:True
- Silver:2:2:True
