name: SeekerJerky_JH
clonePrefabName: 
craftingStation: $piece_cauldron
minStationLevel: 5
maxStationLevelCap: 
repairStation: 
amount: 2
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- BugMeat:2:1:True
- Honey:2:1:True
- MushroomMagecap:1:1:True
