name: sven2legs_Recipe_BlackForge
clonePrefabName: NO
craftingStation: $piece_blackforge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- svenlegs:1:0:True
- FlametalNew:30:10:True
- WolfPelt:20:0:True
- SerpentScale:15:5:True
