name: BoltIron_OdinShip_Recipe_Custom
clonePrefabName: NO
craftingStation: Carpenters Table
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- RoundLog:5:0:True
- Iron:1:0:True
