name: BMR_SeekerScroll_Recipe_Custom
clonePrefabName: NO
craftingStation: $bmr_spell_table
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 5
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- BMR_PaperAncient:5:0:True
- TrophySeeker:5:0:True
