name: Recipe_ScholarFireStaff
clonePrefabName: NO
craftingStation: $piece_workbench
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- GreydwarfEye:50:25:True
- Bronze:10:5:True
- Ruby:5:2:True
- FineWood:20:10:True
