name: WizardBackpack_Recipe_Custom
clonePrefabName: NO
craftingStation: $piece_wizardtable_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- FabricBundle_Plains_TW:2:4:True
- BlackMetal:2:4:True
