name: warlordchest_Recipe_BlackForge
clonePrefabName: NO
craftingStation: $piece_blackforge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- FlametalNew:15:5:True
- BlackMarble:15:10:True
- Softtissue:15:0:True
- Chain:15:0:True
