name: Recipe_SBlackSoup_RtD
clonePrefabName: NO
craftingStation: $piece_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- RawMeat:3:0:True
- Carrot:5:0:True
- Bloodbag:2:0:True
