name: TrollBackpack_Recipe_Forge
clonePrefabName: NO
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- HelmetTrollLeather:1:0:True
- ArmorTrollLeatherChest:1:0:True
- ArmorTrollLeatherLegs:1:0:True
- CapeTrollHide:1:0:True
- TrollHide:0:5:True
- BoneFragments:0:3:True
- Iron:0:10:True
- TrollHide:0:10:True
- BoneFragments:0:6:True
- Silver:0:10:True
- TrollHide:0:15:True
- BoneFragments:0:9:True
- BlackMetal:0:10:True
- TrollHide:0:20:True
- BoneFragments:0:12:True
- Carapace:0:10:True
