name: Recipe_STurnipStew_RtD
clonePrefabName: NO
craftingStation: $piece_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- DeerMeat:3:0:True
- Turnip:6:0:True
- Bloodbag:2:0:True
