name: WispPotion_JH
clonePrefabName: 
craftingStation: $piece_meadcauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 3
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Wisp:3:0:True
- MeadTasty:3:1:True
