name: ss_barblegs_Recipe_Forge
clonePrefabName: NO
craftingStation: $piece_forge
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Silver:20:0:True
- BlackMetal:20:10:True
- LoxPelt:20:100:True
- TrophyHatchling:5:0:True
