name: bphelm_Recipe_Forge
clonePrefabName: NO
craftingStation: $piece_forge
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- BlackMetal:20:5:True
- TrophyGoblinBrute:1:0:True
- WitheredBone:5:3:True
