name: Recipe_ShawDivineElixerBase
clonePrefabName: NO
craftingStation: $piece_meadcauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: $piece_meadcauldron
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Thunderstorm_Item:10:4:True
- GemstoneBlue:1:1:True
- MeadHealthMajor:1:1:True
- MeadEitrMinor:1:1:True
- MeadStaminaMedium:1:1:True
- MeadHealthLingering:1:1:True
- MeadEitrLingering:1:1:True
- MeadStaminaLingering:1:1:True
