name: WishboneBackpack_Recipe_Forge
clonePrefabName: NO
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Bronze:5:0:True
- DeerHide:10:0:True
- LeatherScraps:10:0:True
- Wishbone:1:0:True
- Iron:0:5:True
- ElderBark:0:10:True
- Guck:0:2:True
- Silver:0:5:True
- WolfPelt:0:3:True
- JuteRed:0:2:True
- BlackMetal:0:5:True
- LinenThread:0:10:True
- LoxPelt:0:2:True
- JuteBlue:0:5:True
- ScaleHide:0:5:True
- Carapace:0:5:True
