name: BMR_FireScroll4_Recipe_Custom
clonePrefabName: NO
craftingStation: $bmr_spell_table
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 10
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- BMR_FireScroll3:20:0:True
- BMR_FireEssence:5:0:True
- AncientSeed:2:0:True
