name: Recipe_UncookedFeastofthegods
clonePrefabName: NO
craftingStation: $piece_preptable
minStationLevel: 1
maxStationLevelCap: 
repairStation: $piece_preptable
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- LoxPieUncooked:1:1:True
- FishAndBreadUncooked:1:1:True
- MeatPlatterUncooked:1:1:True
- MisthareSupremeUncooked:1:1:True
- MagicallyStuffedShroomUncooked:1:1:True
- BreadDough:1:1:True
- HoneyGlazedChickenUncooked:1:1:True
- RoastedCrustPie:1:1:True
