name: BronzeCrowbillHTD
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: $piece_forge
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Wood:4:0:True
- Bronze:8:3:True
- LeatherScraps:2:0:True
