name: FishStew_JH
clonePrefabName: 
craftingStation: $piece_cauldron
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- FishCooked:1:1:True
- Onion:2:1:True
- Honey:5:1:True
