name: Recipe_PlainsMageCape_RtD
clonePrefabName: NO
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- BlackMetal:3:2:True
- LinenThread:5:2:True
- Tar:5:2:True
- LoxPelt:3:2:True
