name: Flask_of_the_Gods_Recipe_Custom
clonePrefabName: NO
craftingStation: $pp_alchemy_table
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Potion_Meadbase:1:0:True
- Thistle:4:0:True
- Flax:4:0:True
- Carrot:2:0:True
