name: CaulkedWood_Recipe_Custom
clonePrefabName: NO
craftingStation: Carpenters Table
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 10
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- FineWood:10:0:True
- Resin:10:0:True
- Coal:10:0:True
