name: Recipe_SilverRing
clonePrefabName: NO
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Silver:4:1:True
- Tin:6:1:True
