name: Recipe_ShawesomeCape
clonePrefabName: NO
craftingStation: $piece_blackforge
minStationLevel: 2
maxStationLevelCap: 
repairStation: $piece_blackforge
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- shawfirelegs:1:1:True
- shawfirechest:1:1:True
- shawfirehelm:1:1:True
- FlametalNew:20:4:True
