name: Recipe_MeldursonCape
clonePrefabName: NO
craftingStation: $piece_blackforge
minStationLevel: 2
maxStationLevelCap: 
repairStation: $piece_blackforge
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- RawMeat:200:5:True
- Mushroom:200:5:True
- Carrot:200:5:True
- DragonEgg:1:1:True
- TrophyDragonQueen:1:1:True
- TrophyHatchling:1:1:True
- TrophySGolem:1:1:True
- HasTamed_Item:10:1:True
