name: Recipe_DeathBlade
clonePrefabName: NO
craftingStation: $piece_forge
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Needle:5:5:True
- BlackMetal:10:5:True
- SilverNecklace:1:1:True
