name: BMR_AncientWand_Recipe_BlackForge
clonePrefabName: NO
craftingStation: $piece_blackforge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- GemstoneRed:1:0:True
- CelestialFeather:1:0:True
- YggdrasilWood:26:13:True
- Blackwood:16:8:True
- CharredBone:0:1:True
