name: skoglegs_Recipe_Forge
clonePrefabName: NO
craftingStation: $piece_forge
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Silver:20:10:True
- JuteRed:15:0:True
- WolfHairBundle:15:5:True
