name: DandelionTea_JH
clonePrefabName: 
craftingStation: $piece_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 2
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Dandelion:5:1:True
- Thistle:5:1:True
