name: Recipe_SunBlock4000
clonePrefabName: NO
craftingStation: $piece_blackforge
minStationLevel: 2
maxStationLevelCap: 
repairStation: $piece_blackforge
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- TrophyUlv:1:1:True
- TrophyDragonQueen:1:1:True
- YmirRemains:10:4:True
