name: wslegs_Recipe_BlackForge
clonePrefabName: NO
craftingStation: $piece_blackforge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- lagipants:1:0:True
- valklegs:1:0:True
- svenlegs:1:0:True
- Eitr:20:10:True
- FlametalNew:0:15:True
