name: Recipe_AshLandsMageHood_RtD
clonePrefabName: NO
craftingStation: $piece_blackforge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- FlametalNew:2:2:True
- AskHide:15:2:True
- Grausten:5:2:True
- CharredBone:2:2:True
