name: BMR_IceScroll5_Recipe_Custom
clonePrefabName: NO
craftingStation: $bmr_spell_table
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- BMR_PaperAncient:20:0:True
- BMR_IceEssence:5:0:True
- FreezeGland:5:0:True
- Cloudberry:20:0:True
