name: ThrowAxeBlackmetal_TW_Recipe_Forge
clonePrefabName: NO
craftingStation: $piece_forge
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 5
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- FineWood:20:0:True
- LinenThread:5:0:True
- BlackMetal:20:0:True
