name: LoxJerky_JH
clonePrefabName: 
craftingStation: $piece_cauldron
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 2
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- LoxMeat:2:1:True
- Honey:2:1:True
- Cloudberry:1:1:True
