name: Flask_of_Second_Wind_Recipe_Custom
clonePrefabName: NO
craftingStation: $pp_alchemy_table
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Potion_Meadbase:1:0:True
- Ooze:4:0:True
- FreezeGland:2:0:True
- Feathers:6:0:True
