name: BMR_HealScroll2_Recipe_Custom
clonePrefabName: NO
craftingStation: $bmr_spell_table
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 10
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- BMR_HealScroll1:20:0:True
- AncientSeed:1:0:True
