name: BMR_ClusterBombScroll_Recipe_Custom
clonePrefabName: NO
craftingStation: $bmr_spell_table
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- BMR_PaperAncient:20:0:True
- FlametalOreNew:10:0:True
- SulfurStone:5:0:True
- ProustitePowder:10:0:True
