name: Recipe_MountainIceWand_RtD
clonePrefabName: NO
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- ElderBark:20:2:True
- Silver:1:2:True
- Obsidian:10:2:True
- FreezeGland:2:2:True
