name: SerpentJerky_JH
clonePrefabName: 
craftingStation: $piece_cauldron
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 2
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- SerpentMeat:2:1:True
- Honey:2:1:True
