name: Recipe_spearodingungnir
clonePrefabName: NO
craftingStation: $piece_blackforge
minStationLevel: 2
maxStationLevelCap: 
repairStation: $piece_blackforge
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- ShawesomeCape:1:1:True
- Thunderstorm_Item:10:4:True
- FlametalNew:10:4:True
- Buildnir:1:1:True
