name: BMR_CrimsonLegs
clonePrefabName: BMR_CrimsonLegs
craftingStation: $piece_arcaneanvil_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: $piece_arcaneanvil_TW
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- GemstoneRed:1:0:True
- AskHide:21:10:True
- CharredBone:12:6:True
- FlametalNew:20:10:True
