name: BMR_SeekerCape
clonePrefabName: BMR_SeekerCape
craftingStation: $piece_arcaneanvil_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: $piece_arcaneanvil_TW
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Mandible:1:0:True
- ScaleHide:8:4:True
- Carapace:12:2:True
- Eitr:14:7:True
