name: BowOfFrey
clonePrefabName: 
craftingStation: FletcherTable_TW
minStationLevel: 1
maxStationLevelCap: 4
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []`n- YggdrasilWood:20:2
- YggdrasilWood:20:3
- YggdrasilWood:20:4
reqs:
- YggdrasilWood:40:40:True
- WolfPelt:5:5:True
- Ruby:3:3:True
- AmberPearl:3:3:True

