- PrefabName: ArmorBronzeLegs
  Requirements:
  - Skill: Blocking
    Level: 10
    BlockCraft: false
    BlockEquip: true
    EpicMMO: false
    ExhibitionName: 
  - Skill: Swim
    Level: 10
    BlockCraft: true
    BlockEquip: true
    EpicMMO: false
    ExhibitionName: 
- PrefabName: ArmorBronzeChest
  Requirements:
  - Skill: Blocking
    Level: 10
    BlockCraft: false
    BlockEquip: true
    EpicMMO: false
    ExhibitionName: 
  - Skill: Swim
    Level: 10
    BlockCraft: true
    BlockEquip: true
    EpicMMO: false
    ExhibitionName: 
- PrefabName: HelmetBronze
  Requirements:
  - Skill: Blocking
    Level: 10
    BlockCraft: false
    BlockEquip: true
    EpicMMO: false
    ExhibitionName: 
  - Skill: Swim
    Level: 10
    BlockCraft: true
    BlockEquip: true
    EpicMMO: false
    ExhibitionName: 

