name: HelmetPointyHat
clonePrefabName: HelmetPointyHat
craftingStation: $piece_wizardtable_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: $piece_wizardtable_TW
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- DeerHide:3:1:True
- Coal:5:1:True
- Bronze:1:1:True
