name: BWA_GiantCleaver
m_name: <color=#D4AF37>BWA_GiantCleaver</color>
AppendToolTip: \n<color=#696969>Giant's Relic</color>\n<color=#888888>Cannot be crafted — trophy from a mountain titan.\n<i>(2% drop chance from Jotunn, 2 items)</i></color>


