name: BMB_Crossbow_Lightning
clonePrefabName: 
craftingStation: FletcherTable_TW
minStationLevel: 5
maxStationLevelCap: 5
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs:
reqs:
- BlackMetal:25:25:True
- LeatherScraps:20:20:True
- Resin:20:20:True
- FineWood:35:35:True
- FulingTotem:2:2:True
- ThunderStone:3:3:True
