name: BWA_FlametalDagger
m_name: "<color=#D4AF37>BWA_FlametalDagger</color>"
AppendToolTip: "\n<color=#696969>Ashlands Relic</color>\n<color=#888888>Cannot be crafted — claimed from Plains raiders.\n<i>(0.8% drop chance from Goblins)</i></color>"

