name: BWA_DraconicGreatSword
m_name: <color=#D4AF37>BWA_DraconicGreatSword</color>
AppendToolTip: \n<color=#696969>Draconic Relic</color>\n<color=#888888>Cannot be crafted — tribute from the Dragon.\n<i>(2% drop chance from Dragon, 2 items)</i></color>

