name: BWA_FlametalGreatsword
m_name: <color=#D4AF37>BWA_FlametalGreatsword</color>
AppendToolTip: \n<color=#696969>Ashlands Relic</color>\n<color=#888888>Cannot be crafted — forged in Fader's flames.\n<i>(2% drop chance from Fader, 2 items)</i></color>

