name: BWA_DragonBoneGreatsword
m_name: "<color=#D4AF37>BWA_DragonBoneGreatsword</color>"
AppendToolTip: "\n<color=#696969>Dragon Relic</color>\n<color=#888888>Cannot be crafted — tribute from the Dragon.\n<i>(5% drop chance from Moder, 2 items)</i></color>"


