name: BWA_ObsidianGreatsword
m_name: "<color=#D4AF37>BWA_ObsidianGreatsword</color>"
AppendToolTip: "\n<color=#696969>Obsidian Relic</color>\n<color=#888888>Cannot be crafted — carved from glacial obsidian.\n<i>(0.2% drop chance from Stone Golem, 1 item)</i></color>"


