name: BWA_DraconicDagger
m_name: <color=#D4AF37>BWA_DraconicDagger</color>
AppendToolTip: \n<color=#696969>Draconic Relic</color>\n<color=#888888>Cannot be crafted — hatchling-forged trophy.\n<i>(1% drop chance from Hatchlings)</i></color>

