name: BWA_FlametalAxe
m_name: <color=#D4AF37>BWA_FlametalAxe</color>
AppendToolTip: \n<color=#696969>Ashlands Relic</color>\n<color=#888888>Cannot be crafted — seized from Plains champions.\n<i>(0.8% drop chance from Goblin Brutes)</i></color>

