name: BWA_ElvenAxe
m_name: <color=#D4AF37>BWA_ElvenAxe</color>
AppendToolTip: \n<color=#696969>Elven Relic</color>\n<color=#888888>Cannot be crafted — prize from the Dragon's hoard.\n<i>(5% drop chance from Moder, 2 items)</i></color>


