name: warlordchest
m_name: "<color=#D4AF37>warlordchest</color>"
AppendToolTip: "\n<color=#696969>Warlord's Edict</color>\n<color=#888888>Cannot be crafted — tribute from a fallen warlord.\n<i>(~0.8% Yagluth; ~0.2% Goblin Shaman)</i></color>"

