# MagicBows
- enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_S
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_Blessed_S
    amount: 1
  Items:
  - BMB_FieryBow
  - BMB_FrozenBow
  - BMB_LightningBow
  - BMB_SpiritBow
  - BMB_ToxicBow
  - BMB_Crossbow_Fiery
  - BMB_Crossbow_Frozen
  - BMB_Crossbow_Lightning
  - BMB_Crossbow_Spirit
  - BMB_Crossbow_Toxic


