name: BBP_SeekerBow
clonePrefabName: 
craftingStation: FletcherTable_TW
minStationLevel: 5
maxStationLevelCap: 5
repairStation: 
amount: 1
disabled: true
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs:
reqs:
- BlackMetal:20:20:True
- LeatherScraps:15:15:True
- Resin:15:15:True
- FineWood:30:30:True
- YggdrasilWood:15:15:True
- SeekerMeat:5:5:True
