name: BMR_SorcerersHat
clonePrefabName: BMR_SorcerersHat
craftingStation: $piece_wizardtable_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: $piece_wizardtable_TW
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- TrophyLeech:1:1:True
- Feathers:1:1:True
- TrollHide:2:1:True
- Blueberries:10:1:True
