name: BMB_Crossbow_Spirit
clonePrefabName: 
craftingStation: FletcherTable_TW
minStationLevel: 5
maxStationLevelCap: 5
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []`nreqs:
- BlackMetal:25:25:True
- LeatherScraps:20:20:True
- Resin:20:20:True
- FineWood:35:35:True
- Spirit:10:10:True
- YggdrasilWood:10:10:True

