name: BMB_FrozenBow
clonePrefabName: 
craftingStation: FletcherTable_TW
minStationLevel: 5
maxStationLevelCap: 5
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []`nreqs:
- BlackMetal:20:20:True
- LeatherScraps:15:15:True
- Resin:15:15:True
- FineWood:30:30:True
- FreezeGland:3:3:True
- Crystal:5:5:True

