name: BMB_FieryBow
clonePrefabName: 
craftingStation: FletcherTable_TW
minStationLevel: 5
maxStationLevelCap: 5
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []`nreqs:
- BlackMetal:20:20:True
- LeatherScraps:15:15:True
- Resin:15:15:True
- FineWood:30:30:True
- SurtlingCore:3:3:True
- FireResin:10:10:True

