name: HoneyGlazedMeat
clonePrefabName: HoneyGlazedMeat
craftingStation: $piece_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: $piece_cauldron
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- CookedMeat:1:1:True
- Honey:2:1:True
