name: FireSHWSMBlade
m_weight: 0.8
m_name: Malevolent Blade Of Shawesome
m_description: The image of a burning Black Rose takes hold in your mind as your sight fades... The Living Flames makes it clear - Without a strong enough resolve - your mind and soul will be consumed by the Blade's will... It's powers Transcend the boundaries of mortal minds. - "Rise from the Seeds of Oblivion!"
clonePrefabName: 
mockName: 
customIcon: 
material: 
materials: 
customVisual: 
snapshotRotation: 
snapshotOnMaterialChange: true
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack:
  AttackType: Horizontal
  Attack_Animation: swing_longsword
  Attack_Random_Animation: 0
  Chain_Attacks: 3
  Hit_Terrain: true
  Hit_Friendly: false
  Custom_AttackSpeed: 1
  m_attackStamina: 20
  m_eitrCost: 10
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.2
  Attack_Start_Noise: 20
  Attack_Hit_Noise: 30
  Dmg_Multiplier_Per_Missing_Health: 0
  Damage_Multiplier_By_Health_Deficit_Percent: 0
  Stamina_Return_Per_Missing_HP: 0
  DmgMultiplier: 1
  ForceMultiplier: 44
  StaggerMultiplier: 2
  RecoilMultiplier: 0
  SelfDamage: 0
  Attack_Kills_Self: false
  AttackRange: 3
  AttackHeight: 1
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 0
  ReloadTimeMultiplier: 1
  Reload_Stamina_Drain: 0
  Reload_Eitr_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 90
  Attack_Ray_Width: 0.5
  Lower_Dmg_Per_Hit: false
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Reset_Chain_If_hit: None
  SpawnOnHit: 
  SpawnOnHit_Chance: 0
  Attack_status_effect: 
  Attack_status_effect_chance: 
  Raise_Skill_Amount: 1
  Skill_Hit_Type: Character
  Special_Hit_Skill: None
  Special_Hit_Type: None
  Attack_Projectile: 
  Projectile_Vel: 15
  Projectile_Accuraccy: 10
  Projectiles: 1
  Skill_Accuracy: false
  Launch_Angle: 0
  Projectile_Burst: 1
  Burst_Interval: 0
  Destroy_Previous_Projectile: false
  PerBurst_Resource_usage: false
  Looping_Attack: false
  Consume_Item: false
  AEffects: 
  AEffectsPLUS:
    Hit_Effects:
    - name: fx_himminafl_hitRED
      m_enabled: true
      m_variant: -1
      m_attach: false
      m_follow: false
      m_inheritParentRotation: false
      m_inheritParentScale: false
      m_multiplyParentVisualScale: false
      m_randomRotation: false
      m_scale: false
      m_childTransform: ''
    Hit_Terrain_Effects: []
    Start_Effect:
    - name: fx_himminafl_aoeRED
      m_enabled: true
      m_variant: -1
      m_attach: false
      m_follow: false
      m_inheritParentRotation: false
      m_inheritParentScale: false
      m_multiplyParentVisualScale: false
      m_randomRotation: false
      m_scale: false
      m_childTransform: ''
    Trigger_Effect: []
    Trail_Effect: []
    Burst_Effect: []
Secondary_Attack:
  AttackType: Area
  Attack_Animation: dual_knives_secondary
  Attack_Random_Animation: 0
  Chain_Attacks: 0
  Hit_Terrain: true
  Hit_Friendly: false
  Custom_AttackSpeed: 1
  m_attackStamina: 40
  m_eitrCost: 60
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.2
  Attack_Start_Noise: 10
  Attack_Hit_Noise: 50
  Dmg_Multiplier_Per_Missing_Health: 0
  Damage_Multiplier_By_Health_Deficit_Percent: 0
  Stamina_Return_Per_Missing_HP: 0
  DmgMultiplier: 1.5
  ForceMultiplier: 10
  StaggerMultiplier: 1
  RecoilMultiplier: 0
  SelfDamage: 0
  Attack_Kills_Self: false
  AttackRange: 4
  AttackHeight: 0
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 
  ReloadTimeMultiplier: 1
  Reload_Stamina_Drain: 0
  Reload_Eitr_Drain: 
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 90
  Attack_Ray_Width: 14
  Lower_Dmg_Per_Hit: false
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Reset_Chain_If_hit: None
  SpawnOnHit: 
  SpawnOnHit_Chance: 0
  Attack_status_effect: 
  Attack_status_effect_chance: 
  Raise_Skill_Amount: 1
  Skill_Hit_Type: Character
  Special_Hit_Skill: None
  Special_Hit_Type: None
  Attack_Projectile: fx_SHWSM_attack
  Projectile_Vel: 20
  Projectile_Accuraccy: 0
  Projectiles: 4
  Skill_Accuracy: false
  Launch_Angle: 0
  Projectile_Burst: 1
  Burst_Interval: 0
  Destroy_Previous_Projectile: false
  PerBurst_Resource_usage: false
  Looping_Attack: false
  Consume_Item: false
  AEffects: 
  AEffectsPLUS:
    Hit_Effects:
    - name: fx_SHWSM_attack
      m_enabled: true
      m_variant: 0
      m_attach: false
      m_follow: false
      m_inheritParentRotation: false
      m_inheritParentScale: false
      m_multiplyParentVisualScale: false
      m_randomRotation: false
      m_scale: false
      m_childTransform: ''
    Hit_Terrain_Effects: []
    Start_Effect:
    - name: fx_himminafl_aoeRED
      m_enabled: true
      m_variant: -1
      m_attach: false
      m_follow: false
      m_inheritParentRotation: false
      m_inheritParentScale: false
      m_multiplyParentVisualScale: false
      m_randomRotation: false
      m_scale: false
      m_childTransform: ''
    Trigger_Effect: []
    Trail_Effect: []
    Burst_Effect: []
Damage:
  Blunt: 50
  Chop: 20
  Damage: 100
  Fire: 40
  Frost: 0
  Lightning: 20
  Pickaxe: 20
  Pierce: 0
  Poison: 0
  Slash: 50
  Spirit: 20
Damage_Per_Level:
  Blunt: 0
  Chop: 0
  Damage: 100
  Fire: 100
  Frost: 6
  Lightning: 0
  Pickaxe: 0
  Pierce: 0
  Poison: 0
  Slash: 0
  Spirit: 100
Armor:
  armor: 200
  armorPerLevel: 1
FoodStats: 
Moddifiers:
  m_movementModifier: -0.05
  m_EitrRegen: 1
  m_homeItemsStaminaModifier: 0
  m_heatResistanceModifier: 0
  m_jumpStaminaModifier: 0
  m_attackStaminaModifier: 0
  m_blockStaminaModifier: 0
  m_dodgeStaminaModifier: 0
  m_swimStaminaModifier: 0
  m_sneakStaminaModifier: 0
  m_runStaminaModifier: 0
SE_Equip: 
SE_SET_Equip: 
ShieldStats:
  m_blockPower: 300
  m_blockPowerPerLevel: 0
  m_timedBlockBonus: 2
  m_deflectionForce: 20
  m_deflectionForcePerLevel: 5
m_maxStackSize: 1
m_canBeReparied: true
m_destroyBroken: false
m_dodgeable: true
Attack_status_effect: Burning
Attack_status_effect_chance: 1
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 3
m_knockback: 10
m_useDurability: true
m_useDurabilityDrain: 2
m_durabilityDrain: 0
m_maxDurability: 50
m_durabilityPerLevel: 100
m_equipDuration: 0.2
Attach_Override: None
m_skillType: Swords
m_animationState: OneHanded
m_itemType: OneHandedWeapon
m_toolTier: 5
m_maxQuality: 4
m_value: 0
ConsumableStatusEffect: 
AppendToolTip: 
damageModifiers: []
GEffects: 
GEffectsPLUS:
  Hit_Effects:
  - name: vfx_HitSparks
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  - name: sfx_sword_hit
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  - name: fx_hit_camshake
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  Hit_Terrain_Effects: []
  Start_Effect: []
  Hold_Start_Effects: []
  Trigger_Effect:
  - name: fx_swing_camshake
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  Trail_Effect:
  - name: sfx_sword_swing
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
