name: Buildnir
m_weight: 2
m_name: Buildnir
m_description: Only creation's Champion, one who's hands are most blessed, whos mind is most free shall be worthy of the True power of the Forge Gods. May they grace each swing of your hammer...
clonePrefabName: 
mockName: 
customIcon: 
material: 
materials: 
customVisual: 
snapshotRotation: 
snapshotOnMaterialChange: true
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack:
  AttackType: Horizontal
  Attack_Animation: swing_axe
  Attack_Random_Animation: 0
  Chain_Attacks: 3
  Hit_Terrain: true
  Hit_Friendly: false
  Custom_AttackSpeed: 1
  m_attackStamina: 40
  m_eitrCost: 40
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.2
  Attack_Start_Noise: 10
  Attack_Hit_Noise: 60
  Dmg_Multiplier_Per_Missing_Health: 0
  Damage_Multiplier_By_Health_Deficit_Percent: 0
  Stamina_Return_Per_Missing_HP: 0
  DmgMultiplier: 1
  ForceMultiplier: 1
  StaggerMultiplier: 1
  RecoilMultiplier: 0
  SelfDamage: 0
  Attack_Kills_Self: false
  AttackRange: 2.2
  AttackHeight: 0.8
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  ReloadTimeMultiplier: 1
  Reload_Stamina_Drain: 0
  Reload_Eitr_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 90
  Attack_Ray_Width: 0.3
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Reset_Chain_If_hit: Tree
  SpawnOnHit: 
  SpawnOnHit_Chance: 0
  Attack_status_effect: 
  Attack_status_effect_chance: 
  Raise_Skill_Amount: 1
  Skill_Hit_Type: Character
  Special_Hit_Skill: WoodCutting
  Special_Hit_Type: Tree
  Attack_Projectile: 
  Projectile_Vel: 10
  Projectile_Accuraccy: 10
  Projectiles: 1
  Skill_Accuracy: false
  Launch_Angle: 0
  Projectile_Burst: 1
  Burst_Interval: 0
  Destroy_Previous_Projectile: false
  PerBurst_Resource_usage: false
  Looping_Attack: false
  Consume_Item: false
  AEffects: 
  AEffectsPLUS:
    Hit_Effects:
    - name: fx_himminafl_hit
      m_enabled: true
      m_variant: -1
      m_attach: false
      m_follow: false
      m_inheritParentRotation: false
      m_inheritParentScale: false
      m_multiplyParentVisualScale: false
      m_randomRotation: false
      m_scale: false
      m_childTransform: ''
    Hit_Terrain_Effects: []
    Start_Effect: []
    Trigger_Effect: []
    Trail_Effect: []
    Burst_Effect: []
Secondary_Attack:
  AttackType: Projectile
  Attack_Animation: staff_shield
  Attack_Random_Animation: 0
  Chain_Attacks: 0
  Hit_Terrain: true
  Hit_Friendly: false
  Custom_AttackSpeed: 1
  m_attackStamina: 50
  m_eitrCost: 100
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.2
  Attack_Start_Noise: 10
  Attack_Hit_Noise: 40
  Dmg_Multiplier_Per_Missing_Health: 0
  Damage_Multiplier_By_Health_Deficit_Percent: 0
  Stamina_Return_Per_Missing_HP: 0
  DmgMultiplier: 1.5
  ForceMultiplier: 1.5
  StaggerMultiplier: 1
  RecoilMultiplier: 0
  SelfDamage: 0
  Attack_Kills_Self: false
  AttackRange: 0
  AttackHeight: 0.2
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 
  ReloadTimeMultiplier: 1
  Reload_Stamina_Drain: 0
  Reload_Eitr_Drain: 
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 90
  Attack_Ray_Width: 0
  Lower_Dmg_Per_Hit: false
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Reset_Chain_If_hit: None
  SpawnOnHit: 
  SpawnOnHit_Chance: 0
  Attack_status_effect: 
  Attack_status_effect_chance: 
  Raise_Skill_Amount: 1
  Skill_Hit_Type: Character
  Special_Hit_Skill: WoodCutting
  Special_Hit_Type: Tree
  Attack_Projectile: buildnir_aoe
  Projectile_Vel: 0
  Projectile_Accuraccy: 11
  Projectiles: 1
  Skill_Accuracy: false
  Launch_Angle: -5
  Projectile_Burst: 1
  Burst_Interval: 10
  Destroy_Previous_Projectile: false
  PerBurst_Resource_usage: false
  Looping_Attack: false
  Consume_Item: false
  AEffects: 
  AEffectsPLUS:
    Hit_Effects: []
    Hit_Terrain_Effects:
    - name: fx_himminafl_hit
      m_enabled: true
      m_variant: -1
      m_attach: false
      m_follow: false
      m_inheritParentRotation: false
      m_inheritParentScale: false
      m_multiplyParentVisualScale: false
      m_randomRotation: false
      m_scale: false
      m_childTransform: ''
    Start_Effect:
    - name: fx_buildnir_tcloud_start
      m_enabled: true
      m_variant: -1
      m_attach: false
      m_follow: false
      m_inheritParentRotation: false
      m_inheritParentScale: false
      m_multiplyParentVisualScale: false
      m_randomRotation: false
      m_scale: false
      m_childTransform: ''
    Trigger_Effect: []
    Trail_Effect: []
    Burst_Effect: []
Damage:
  Blunt: 100
  Chop: 50
  Damage: 100
  Fire: 0
  Frost: 0
  Lightning: 100
  Pickaxe: 50
  Pierce: 0
  Poison: 0
  Slash: 0
  Spirit: 0
Damage_Per_Level:
  Blunt: 0
  Chop: 3
  Damage: 0
  Fire: 0
  Frost: 0
  Lightning: 0
  Pickaxe: 0
  Pierce: 0
  Poison: 0
  Slash: 5
  Spirit: 0
Armor:
  armor: 100
  armorPerLevel: 1
FoodStats: 
Moddifiers:
  m_movementModifier: 0
  m_EitrRegen: 0.01
  m_homeItemsStaminaModifier: 0
  m_heatResistanceModifier: 0
  m_jumpStaminaModifier: 0
  m_attackStaminaModifier: 0
  m_blockStaminaModifier: 0
  m_dodgeStaminaModifier: 0
  m_swimStaminaModifier: 0
  m_sneakStaminaModifier: 0
  m_runStaminaModifier: 0
SE_Equip: 
SE_SET_Equip: 
ShieldStats:
  m_blockPower: 100
  m_blockPowerPerLevel: 0
  m_timedBlockBonus: 2
  m_deflectionForce: 20
  m_deflectionForcePerLevel: 5
m_maxStackSize: 1
m_canBeReparied: true
m_destroyBroken: false
m_dodgeable: true
Attack_status_effect: Lightning
Attack_status_effect_chance: 1
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 3
m_knockback: 100
m_useDurability: true
m_useDurabilityDrain: 15
m_durabilityDrain: 0
m_maxDurability: 500
m_durabilityPerLevel: 500
m_equipDuration: 0.2
Attach_Override: Tool
m_skillType: Axes
m_animationState: OneHanded
m_itemType: OneHandedWeapon
m_toolTier: 4
m_maxQuality: 4
m_value: 0
ConsumableStatusEffect: 
AppendToolTip: 
damageModifiers: []
GEffects: 
GEffectsPLUS:
  Hit_Effects:
  - name: vfx_HitSparks
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  - name: sfx_axe_hit
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  - name: fx_hit_camshake
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  - name: fx_jotunbane_hit
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  Hit_Terrain_Effects: []
  Start_Effect: []
  Hold_Start_Effects: []
  Trigger_Effect:
  - name: fx_swing_camshake
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  Trail_Effect: []
