name: dhakharianhelm
m_weight: 4
m_name: Fabricator-General Helm
m_description: '"Fabricator-General" is also the title given to the Arch Magos who holds political and doctrinal sway as the planetary governor over any other individual Forge World of the Mechanicus by dint of their superior knowledge and insight into their chosen field. '
clonePrefabName: 
mockName: 
customIcon: 
material: 
materials: 
customVisual: 
snapshotRotation: 
snapshotOnMaterialChange: true
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack: 
Secondary_Attack: 
Damage: 
Damage_Per_Level: 
Armor:
  armor: 15
  armorPerLevel: 15
FoodStats: 
Moddifiers:
  m_movementModifier: 0
  m_EitrRegen: 1.1
  m_homeItemsStaminaModifier: 0
  m_heatResistanceModifier: 0
  m_jumpStaminaModifier: 0
  m_attackStaminaModifier: 0
  m_blockStaminaModifier: 0
  m_dodgeStaminaModifier: 0
  m_swimStaminaModifier: 0
  m_sneakStaminaModifier: 0
  m_runStaminaModifier: 0
SE_Equip:
  EffectName: Arcanium_Maximus_SE
SE_SET_Equip:
  SetName: Rainment of the Skitarii
  Size: 3
  EffectName: valkwings_se1
ShieldStats:
  m_blockPower: 10
  m_blockPowerPerLevel: 0
  m_timedBlockBonus: 1.5
  m_deflectionForce: 0
  m_deflectionForcePerLevel: 0
m_maxStackSize: 1
m_canBeReparied: true
m_destroyBroken: false
m_dodgeable: true
Attack_status_effect: 
Attack_status_effect_chance: 1
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 4
m_knockback: 30
m_useDurability: true
m_useDurabilityDrain: 4
m_durabilityDrain: 0
m_maxDurability: 2000
m_durabilityPerLevel: 500
m_equipDuration: 1
Attach_Override: None
m_skillType: Swords
m_animationState: OneHanded
m_itemType: Helmet
m_toolTier: 0
m_maxQuality: 4
m_value: 0
ConsumableStatusEffect: 
AppendToolTip: 
damageModifiers:
- Spirit:Immune
GEffects: 
GEffectsPLUS:
  Hit_Effects: []
  Hit_Terrain_Effects: []
  Start_Effect: []
  Hold_Start_Effects: []
  Trigger_Effect: []
  Trail_Effect: []
