# WeaponAdditions (blacks7ar)

# Weapons - A tier (mid-high)
- enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_A
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_Blessed_A
    amount: 1
  Items:
  - BWA_DragonBlade
  - BWA_DragonBoneGreatsword
  - BWA_DraconicDagger
  - BWA_DraconicGreatSword
  - BWA_DraconicScythe
  - BWA_DraconicSword
  - BWA_FlametalDagger
  - BWA_FlametalGreatsword
  - BWA_FlametalHammer
  - BWA_FlametalAxe
  - BWA_FlametalPolearm
  - BWA_FlametalScythe
  - BWA_FlametalSword

# Weapons - S tier (end-game elven)
- enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_S
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_Blessed_S
    amount: 1
  Items:
  - BWA_ElvenAxe
  - BWA_ElvenHammer
  - BWA_ElvenSword
  - BWA_ElvenSpear

# Shields - S tier (end-game elven)
- enchant_prefab:
    prefab: kg_EnchantScroll_Armor_S
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Armor_Blessed_S
    amount: 1
  Items:
  - BWA_ElvenShield


# Weapons - A tier (giant/obsidian mid-high)
- enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_A
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_Blessed_A
    amount: 1
  Items:
  - BWA_GiantAxe
  - BWA_GiantCleaver
  - BWA_giantMace
  - BWA_ObsidianGreatsword

# Shields - A tier (obsidian mid-high)
- enchant_prefab:
    prefab: kg_EnchantScroll_Armor_A
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Armor_Blessed_A
    amount: 1
  Items:
  - BWA_ObsidianBuckler

