# BowPlugin (blacks7ar)

# Weapons - Crossbows by tier
- enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_F
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_Blessed_F
    amount: 1
  Items:
  - BBP_Crossbow_Flint

- enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_D
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_Blessed_D
    amount: 1
  Items:
  - BBP_Crossbow_Bronze

- enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_C
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_Blessed_C
    amount: 1
  Items:
  - BBP_Crossbow_Iron

- enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_B
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_Blessed_B
    amount: 1
  Items:
  - BBP_Crossbow_Silver

- enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_A
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_Blessed_A
    amount: 1
  Items:
  - BBP_Crossbow_BlackMetal

# Weapons - Bows by tier
- enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_D
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_Blessed_D
    amount: 1
  Items:
  - BBP_BoneBow

- enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_A
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_Blessed_A
    amount: 1
  Items:
  - BBP_SilverBow
  - BBP_BlackMetalBow

- enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_S
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_Blessed_S
    amount: 1
  Items:
  - BBP_ElvenBow
  - BBP_SeekerBow


