name: BBH_Seeker_Quiver
clonePrefabName: 
craftingStation: FletcherTable_TW
minStationLevel: 1
maxStationLevelCap: 4
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []`n- YggdrasilWood:1:2
- YggdrasilWood:2:3
- YggdrasilWood:3:4
reqs:
- YggdrasilWood:1:1:True
- Carapace:1:1:True
- Mandible:4:4:True

