name: BBH_BlackForest_Bow
clonePrefabName: 
craftingStation: FletcherTable_TW
minStationLevel: 2
maxStationLevelCap: 5
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []`n- Bronze:10:3
- Bronze:20:4
- Bronze:30:5
reqs:
- Bronze:15:15:True
- LeatherScraps:8:8:True
- Resin:8:8:True
- FineWood:20:20:True

