name: BBH_Lox_Quiver
clonePrefabName: 
craftingStation: FletcherTable_TW
minStationLevel: 2
maxStationLevelCap: 5
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs:
- SerpentScale:2:3
- SerpentScale:4:4
- SerpentScale:6:5
reqs:
- FineWood:15:15:True
- SerpentScale:5:5:True
- LoxPelt:3:3:True

