name: BBH_Surtling_Bow
clonePrefabName: 
craftingStation: FletcherTable_TW
minStationLevel: 4
maxStationLevelCap: 5
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs:
- Iron:10:5
reqs:
- Iron:20:20:True
- LeatherScraps:12:12:True
- Resin:12:12:True
- FineWood:25:25:True
- SurtlingCore:2:2:True
