groups:
  Huge Wood Gain:
  - Wood
  - Fine Wood
  - Core Wood
  - Ancient Bark
  MeadBase:
  - BarleyWineBase
  - MeadBaseTamer
  - MeadBaseSwimmer
  - MeadBaseLightFoot
  - MeadBaseStrength
  - MeadBaseBugRepellent
  - MeadBaseBzerker
  - MeadBaseHasty
  - MeadBaseEitrMinor
  - MeadBaseFrostResist
  - MeadBaseHealthMajor
  - MeadBaseHealthMedium
  - MeadBaseHealthMinor
  - MeadBasePoisonResist
  - MeadBaseStaminaLingering
  - MeadBaseStaminaMedium
  - MeadBaseStaminaMinor
  - MeadBaseTasty
  - MeadBaseEitrLingering
  - MeadBaseHealthLingering
  - MeadBaseLightningResist_TW
  - MeadBaseLingeringStaminaMinor_TW
  - MeadBaseLingeringStaminaMedium_TW
  - MeadBaseEitrBlackForest_TW
  - MeadBaseEitrMountain_TW
  CustomFood:
  - HoneyGlazedDeer
  - HoneyGlazedMeat
  - HoneyGlazedNeck
  - HoneyGlazedLox
  - HoneyGlazedFish
  - HoneyGlazedWolf
  - JellyGlazedHare
  - JellyGlazedSeeker
  - CookedEntrails
  - ElkJerky
  - LoxJerky_JH
  - SeekerJerky_JH
  - FishJerky_JH
  - FishStew_JH
  - NeckJerky_JH
  - SerpentJerky_JH
  - FishNLoxSkewer
  - FishMeatSkewer
  - DandelionTea_JH
  CookingAdditionsSoups:
  - BCA_ChickenSoup
  - BCA_FishSoup
  - BCA_MeatSoup
  - BCA_TomatoSoup
  - BCA_VeggieSoup
  CookingAdditionsPreparedFoods:
  - BCA_BoiledEgg
  - BCA_SpicyMeatPlatter
  - BCA_SpicyMeatSupreme
  - BCA_SpicySerpentMeat
  - BCA_SweetNSpicyFish
  CookingAdditionsSaltedMeats:
  - BCA_Undryed_AsksvinMeat
  - BCA_Undryed_BugMeat
  - BCA_Undryed_ChickenMeat
  - BCA_Undryed_DeerMeat
  - BCA_Undryed_Fish
  - BCA_Undryed_HareMeat
  - BCA_Undryed_RawMeat
  - BCA_Undryed_WolfMeat
  CookingAdditionsIngredients:
  - BCA_ChiliPepperSeeds
  - BCA_TomatoSeeds
  - BCA_Salt
  CookingAdditionsCoatedEggs:
  - BCA_Coated_AsksvinEgg
  - BCA_Coated_ChickenEgg
  - BCA_Coated_VoltureEgg
  ReduceWeight:
  - Stone
  - BlackMarble
  - Flint
  - Coal
  - Tar
  - Obsidian
  - SulfurStone
  - Grausten
  - Chitin
  - CeramicPlate
  WizardryScrolls:
  - ArcaneScroll_DamageBuff_TW
  - ArcaneScroll_SpeedBuff_TW
  - ArcaneScroll_JumpBuff_TW
  - ArcaneScroll_SlowfallBuff_TW
  MetalsDeepNorth:
  - RagnoriteBar_TW
  - TyraniumBar_TW
  - ThoradusBar_TW
  - LokvyrBar_TW
  - RagnoriteOre_TW
  - TyraniumOre_TW
  - LokvyrOre_TW
#
