# More World Locations - Pickable Items Lists
# Underground Ruins pickable items for dangerous Black Forest dungeon
# Aligned with CONTINUE.md material-focused economy philosophy
# Enhanced rewards to compensate for high-risk dungeon exploration

UndergroundRuinsPickables1:
  # Underground dungeon pickables - Premium materials scattered throughout dungeon
  # Focus: Valuable pickable items that reward thorough exploration
  # Compensated for dungeon rarity and danger with enhanced rewards
  - item: Coins
    stackMin: 8
    stackMax: 25
  - item: Amber
    stackMin: 1
    stackMax: 4
  - item: Ruby
    stackMin: 1
    stackMax: 3
  - item: DustMagic
    stackMin: 2
    stackMax: 5
  - item: RunestoneMagic
    stackMin: 1
    stackMax: 3
  - item: EssenceMagic
    stackMin: 1
    stackMax: 2
  - item: BoneFragments
    stackMin: 2
    stackMax: 6
  - item: LeatherScraps
    stackMin: 1
    stackMax: 4
  - item: Resin
    stackMin: 2
    stackMax: 6
  - item: Coal
    stackMin: 2
    stackMax: 5

CatacombPickables1:
  # Forbidden Catacombs pickables - Mixed treasures scattered throughout both sections
  # Focus: Noble wealth mixed with desperate remnants of the suffering masses
  # Compensated for dungeon rarity and dual-section danger with enhanced rewards
  - item: Coins
    stackMin: 10
    stackMax: 30
  - item: Amber
    stackMin: 2
    stackMax: 5
  - item: Ruby
    stackMin: 1
    stackMax: 4
  - item: DustMagic
    stackMin: 2
    stackMax: 5
  - item: RunestoneMagic
    stackMin: 1
    stackMax: 3
  - item: EssenceMagic
    stackMin: 1
    stackMax: 2
  - item: DustRare
    stackMin: 1
    stackMax: 3
  - item: BoneFragments
    stackMin: 3
    stackMax: 8
  - item: LeatherScraps
    stackMin: 2
    stackMax: 6
  - item: Resin
    stackMin: 3
    stackMax: 8
  - item: Coal
    stackMin: 3
    stackMax: 7 