CatacombLoot1:
- item: DustMagic
  stackMax: 8
  stackMin: 4
  weight: 3.0
- item: RunestoneMagic
  stackMax: 6
  stackMin: 3
  weight: 2.5
- item: EssenceMagic
  stackMax: 5
  stackMin: 2
  weight: 2.0
- item: ShardMagic
  stackMax: 6
  stackMin: 3
  weight: 2.0
- item: DustRare
  stackMax: 5
  stackMin: 2
  weight: 2.0
- item: RunestoneRare
  stackMax: 4
  stackMin: 1
  weight: 1.5
- item: EssenceRare
  stackMax: 3
  stackMin: 1
  weight: 1.2
- item: Amber
  stackMax: 7
  stackMin: 3
  weight: 2.0
- item: Ruby
  stackMax: 5
  stackMin: 2
  weight: 1.8
- item: Coins
  stackMax: 40
  stackMin: 20
  weight: 2.2
- item: BoneFragments
  stackMax: 8
  stackMin: 3
  weight: 1.5
- item: LeatherScraps
  stackMax: 6
  stackMin: 2
  weight: 1.2
- item: Flint
  stackMax: 10
  stackMin: 5
  weight: 1.5
- item: Feathers
  stackMax: 15
  stackMin: 6
  weight: 1.5
- item: Resin
  stackMax: 12
  stackMin: 4
  weight: 1.0
- item: Wood
  stackMax: 25
  stackMin: 10
  weight: 1.0
- item: Stone
  stackMax: 20
  stackMin: 8
  weight: 1.2
- item: Coal
  stackMax: 10
  stackMin: 4
  weight: 1.0
- item: Coins
  stackMax: 50
  stackMin: 10
  weight: 0.6
- item: Amber
  stackMax: 1
  stackMin: 1
  weight: 0.2
- item: AmberPearl
  stackMax: 1
  stackMin: 1
  weight: 0.08

 

UndergroundRuinsLoot1:
- item: DustMagic
  stackMax: 10
  stackMin: 5
  weight: 3.0
- item: RunestoneMagic
  stackMax: 8
  stackMin: 4
  weight: 2.5
- item: EssenceMagic
  stackMax: 6
  stackMin: 3
  weight: 2.0
- item: ShardMagic
  stackMax: 7
  stackMin: 4
  weight: 2.0
- item: DustRare
  stackMax: 6
  stackMin: 3
  weight: 2.2
- item: RunestoneRare
  stackMax: 5
  stackMin: 2
  weight: 1.8
- item: EssenceRare
  stackMax: 4
  stackMin: 2
  weight: 1.6
- item: DustEpic
  stackMax: 3
  stackMin: 1
  weight: 1.2
- item: RunestoneEpic
  stackMax: 3
  stackMin: 1
  weight: 1.0
- item: EssenceEpic
  stackMax: 2
  stackMin: 1
  weight: 0.8
- item: Amber
  stackMax: 6
  stackMin: 2
  weight: 1.8
- item: Ruby
  stackMax: 4
  stackMin: 1
  weight: 1.5
- item: Coins
  stackMax: 35
  stackMin: 15
  weight: 2.0
- item: BoneFragments
  stackMax: 10
  stackMin: 4
  weight: 1.5
- item: LeatherScraps
  stackMax: 8
  stackMin: 3
  weight: 1.2
- item: Flint
  stackMax: 12
  stackMin: 6
  weight: 1.5
- item: Feathers
  stackMax: 18
  stackMin: 7
  weight: 1.5
- item: Resin
  stackMax: 15
  stackMin: 5
  weight: 1.0
- item: Wood
  stackMax: 30
  stackMin: 12
  weight: 1.0
- item: Stone
  stackMax: 25
  stackMin: 10
  weight: 1.2
- item: Coal
  stackMax: 12
  stackMin: 5
  weight: 1.0
- item: Coins
  stackMax: 50
  stackMin: 10
  weight: 0.8
- item: Amber
  stackMax: 1
  stackMin: 1
  weight: 0.3
- item: AmberPearl
  stackMax: 1
  stackMin: 1
  weight: 0.1

version: '2.0'
