name: ArrowFrost_Recipe_FletcherTable
clonePrefabName: NO
craftingStation: FletcherTable_TW
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Wood:8:0:True
- Obsidian:4:0:True
- Feathers:2:0:True
- FreezeGland:1:0:True
