name: StaffVulkarion_TW
m_name: <color=#D4AF37>$staff_vulkarion_TW</color>
AppendToolTip: \n<color=#696969>Vulkarion's Decree</color>\n<color=#888888>Cannot be crafted — forged in primordial fire.\n<i>(5% drop chance from Surtr)</i></color>

