name: StaffStorm_TW
m_name: <color=#D4AF37>$staff_storm_TW</color>
AppendToolTip: \n<color=#696969>Tempest Caller</color>\n<color=#888888>Cannot be crafted — mastery of storm and sea.\n<i>(3% from Storm Herald; 3% from Sea Serpent)</i></color>

