name: JVLmock_Pickable_BlackCoreStand
itemPrefab: JVLmock_BlackCore
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: ''
respawnTimer: 0
spawnOffset: 1.2
ifHasHealth: 
hiddenChildWhenPicked: core
extraDrops: 
