name: BCA_ChiliPepperPlant
itemPrefab: BCA_ChiliPepper
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: ''
respawnTimer: 300
spawnOffset: 1
ifHasHealth: 30
hiddenChildWhenPicked: Chilis
extraDrops: 
