name: JVLmock_Pickable_DvergrMineTreasure
itemPrefab: JVLmock_Coins
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: $piece_treasure_pile
respawnTimer: 0
spawnOffset: 0.5
ifHasHealth: 
hiddenChildWhenPicked: 
extraDrops:
  drops:
  - JVLmock_Coins
  dropMin: 1
  dropMax: 4
  dropChance: 1
  dropOneOfEach: false
