name: JVLmock_Pickable_Onion
itemPrefab: JVLmock_Onion
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: ''
respawnTimer: 0
spawnOffset: 0.5
ifHasHealth: 1
hiddenChildWhenPicked: 
extraDrops: 
