name: JVLmock_Pickable_SeedCarrot
itemPrefab: JVLmock_CarrotSeeds
cloneOfWhatPickable: 
material: 
amount: 3
size: 
overrideName: ''
respawnTimer: 0
spawnOffset: 0.5
ifHasHealth: 1
hiddenChildWhenPicked: 
extraDrops: 
