name: BCA_TomatoPlant
itemPrefab: BCA_Tomato
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: ''
respawnTimer: 300
spawnOffset: 1
ifHasHealth: 30
hiddenChildWhenPicked: Tomatos
extraDrops: 
