name: Pickable_SmokePuff
itemPrefab: MushroomSmokePuff
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: ''
respawnTimer: 100
spawnOffset: 0.5
ifHasHealth: 
hiddenChildWhenPicked: visual
extraDrops: 
