name: JVLmock_Pickable_Flint
itemPrefab: JVLmock_Flint
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: ''
respawnTimer: 240
spawnOffset: 0.5
ifHasHealth: 
hiddenChildWhenPicked: model
extraDrops: 
