name: JVLmock_Pickable_Stone
itemPrefab: JVLmock_Stone
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: ''
respawnTimer: 0
spawnOffset: 0.5
ifHasHealth: 
hiddenChildWhenPicked: 
extraDrops: 
