name: BlueberryBush
itemPrefab: Blueberries
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: ''
respawnTimer: 220
spawnOffset: 1
ifHasHealth: 30
hiddenChildWhenPicked: Berrys
extraDrops: 
