name: JVLmock_Pickable_ForestCryptRemains02
itemPrefab: JVLmock_BoneFragments
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: $item_pickable_skeletalremains
respawnTimer: 0
spawnOffset: 0.5
ifHasHealth: 
hiddenChildWhenPicked: 
extraDrops: 
