name: JVLmock_Pickable_Branch
itemPrefab: JVLmock_Wood
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: $item_pickable_branch
respawnTimer: 240
spawnOffset: 0.5
ifHasHealth: 
hiddenChildWhenPicked: model
extraDrops: 
