name: Pickable_SurtlingCoreStand (1)
itemPrefab: JVLmock_SurtlingCore
cloneOfWhatPickable: 
material: 
amount: 1
size: 
overrideName: ''
respawnTimer: 0
spawnOffset: 0.926
ifHasHealth: 
hiddenChildWhenPicked: core
extraDrops: 
