---
# Enhanced Creature Lists for More World Locations
# Optimized for reduced spawn quantities with increased variety and excitement
# Aligned with CONTINUE.md material-focused economy and thematic consistency

# Combined Creature Lists - Reduced from 28 → 11 groups
# Preserving all spawn variety while eliminating duplication

MeadowsCreatures_Standard:
  - Skeleton
  - Skeleton_Poison
  - Skeleton_NoArcher

BlackforestCreatures_Standard:
  - Greydwarf
  - Greydwarf_Elite
  - Greydwarf_Shaman

BlackforestPack2Creatures:
  - Greydwarf
  - Greydwarf_Elite
  - Greydwarf_Shaman

MountainsCreatures_Standard:
  - Wolf
  - Ulv
  - Hatchling

MistlandsCreatures_Full:
  - Seeker
  - SeekerBrute
  - Tick
  - Gjall

MistlandsCreatures_Light:
  - Seeker
  - SeekerBrute
  - Gjall

SwampCreatures_Standard:
  - Skeleton
  - Skeleton_Poison
  - Skeleton_NoArcher
  - Draugr
  - Draugr_Elite
  - Wraith

CatacombCreatures_Expanded:
  - Skeleton
  - Skeleton_Poison
  - Skeleton_NoArcher
  - Wraith

# Meadows Pack 1 - Enhanced Creature Variety
# Combined into MeadowsCreatures_Standard
# Meadows Pack 2 Barns - peaceful farm animal spawns
MeadowsCreatures5:
  - Boar
# Black Forest Pack 1 - Enhanced Creature Variety
# Combined into BlackforestCreatures_Standard

# Tavern-specific creature list for social locations
WoodTavernCreatures1:
  # Social locations - Mixed creature types for variety
  # Focus: Balanced challenge with social/tavern themes
  - Greydwarf
  - Greydwarf_Elite
  - Greydwarf_Shaman
  - Skeleton
  - Skeleton_Poison
  - Skeleton_NoArcher
  - Greydwarf
  - Greydwarf_Elite
  - Greydwarf_Shaman
  - Skeleton
  # Elite variants for better materials (40% chance)
  - Greydwarf_Elite
  - Greydwarf_Shaman
  - Skeleton_Poison
  - Skeleton_NoArcher
  - Greydwarf_Elite
  - Greydwarf_Shaman
  # Rare spawns for excitement (25% chance)
  - Skeleton_NoArcher
  - Greydwarf_Shaman
  - Skeleton_Poison
  - Greydwarf_Elite
  - Skeleton_NoArcher

# Black Forest Pack 2 - Enhanced Creature Variety
# Combined into BlackforestPack2Creatures

# Specialized creature lists for specific Black Forest Pack 2 location themes
BlackforestPack2SkullCreatures1:
  # Skull/Death themed locations - Enhanced undead presence
  # Focus: Mixed creatures with undead emphasis for thematic consistency
  - Greydwarf
  - Greydwarf_Elite
  - Greydwarf_Shaman
  - Skeleton
  - Skeleton_Poison
  - Skeleton_NoArcher
  - Greydwarf
  - Skeleton
  - Greydwarf_Elite
  - Skeleton_Poison
  # Elite variants for better materials (40% chance)
  - Greydwarf_Elite
  - Greydwarf_Shaman
  - Skeleton_Poison
  - Skeleton_NoArcher
  - Greydwarf_Elite
  - Skeleton_Poison
  - Greydwarf_Shaman
  - Skeleton_NoArcher
  # Rare spawns for excitement (25% chance)
  - Skeleton_NoArcher
  - Greydwarf_Shaman
  - Skeleton_Poison
  - Greydwarf_Elite
  - Skeleton_NoArcher

BlackforestPack2GraveCreatures1:
  # Grave/Burial themed locations - Enhanced undead focus
  # Focus: Heavy undead presence with some forest creatures
  - Skeleton
  - Skeleton_Poison
  - Skeleton_NoArcher
  - Greydwarf
  - Skeleton
  - Skeleton_Poison
  - Greydwarf_Elite
  - Skeleton_NoArcher
  - Skeleton
  - Greydwarf_Shaman
  # Elite variants for better materials (45% chance)
  - Skeleton_Poison
  - Skeleton_NoArcher
  - Greydwarf_Elite
  - Skeleton_Poison
  - Greydwarf_Shaman
  - Skeleton_NoArcher
  - Greydwarf_Elite
  - Skeleton_Poison
  - Skeleton_NoArcher
  # Rare spawns for excitement (30% chance)
  - Skeleton_NoArcher
  - Greydwarf_Shaman
  - Skeleton_Poison
  - Greydwarf_Elite
  - Skeleton_NoArcher
  - Greydwarf_Shaman

# Underground Ruins - Black Forest Procedural Dungeon
# Thematic consistency with dangerous underground Black Forest environment
# Enhanced elite density to match dungeon danger level
# and material-focused economy

UndergroundRuinsCreatures1:
  # Underground dungeon - Enhanced elite presence for dangerous environment
  # Focus: High-risk, high-reward underground encounters
  # Elite density ~60% to match dungeon difficulty and material economy needs
  - Greydwarf
  - Greydwarf_Elite
  - Greydwarf_Shaman
  - Greydwarf
  - Greydwarf_Elite
  - Greydwarf_Shaman
  - Greydwarf_Elite
  - Greydwarf_Shaman
  - Greydwarf_Elite
  - Greydwarf
  # Heavy elite variants for premium underground materials (60% chance)
  - Greydwarf_Elite
  - Greydwarf_Shaman
  - Greydwarf_Elite
  - Greydwarf_Shaman
  - Greydwarf_Elite
  - Greydwarf_Shaman
  - Greydwarf_Elite
  - Greydwarf_Shaman
  - Greydwarf_Elite
  - Greydwarf_Shaman
  - Greydwarf_Elite
  - Greydwarf_Shaman
  - Greydwarf_Elite
  - Greydwarf_Shaman
  - Greydwarf_Elite
  - Greydwarf_Shaman
  # Maximum elite spawns for ultimate underground excitement (40% chance)
  - Greydwarf_Shaman
  - Greydwarf_Elite
  - Greydwarf
  - Greydwarf
  - Greydwarf
  - Greydwarf
  - Greydwarf
  - Greydwarf
  - Greydwarf
  - Greydwarf

# Forbidden Catacombs - Swamp Biome Procedural Dungeon
# Combined into CatacombCreatures_Expanded

# Mountains Pack 1 - Enhanced Creature Variety
# Combined into MountainsCreatures_Standard

# Plains Pack 1 - Enhanced Creature Variety
# Thematic consistency with Plains biome identity
# Performance optimized with enhanced elite density
# to compensate for reduced spawn quantities

PlainsCreatures1:
  # Common locations - Diverse mix for early Plains progression
  # Focus: Reliable material farming with moderate challenge
  # Enhanced variety to compensate for reduced spawn quantities
  - Goblin
  - Goblin
  - Goblin
  - GoblinShaman
  - GoblinShaman
  - Lox
  - Deathsquito
  - Deathsquito
  - Goblin
  - Goblin
  # Elite variants for better materials (40% chance)
  - GoblinShaman
  - GoblinBrute
  - GoblinShaman
  - GoblinBrute
  - GoblinShaman
  - GoblinBrute
  - GoblinShaman
  - GoblinBrute
  # Rare spawns for excitement (25% chance)
  - GoblinBrute
  - Lox
  - GoblinBrute
  - Lox
  - GoblinBrute

PlainsCreatures2:
  # Uncommon locations - Higher tier creatures for better rewards
  # Focus: Premium materials and rare drops for mid-tier progression
  # Enhanced elite density to compensate for reduced spawn quantities
  - Goblin
  - Goblin
  - GoblinShaman
  - GoblinShaman
  - GoblinBrute
  - GoblinBrute
  - Lox
  - Deathsquito
  - Goblin
  - GoblinShaman
  # Elite variants for premium materials (50% chance)
  - GoblinShaman
  - GoblinBrute
  - GoblinShaman
  - GoblinBrute
  - GoblinShaman
  - GoblinBrute
  - GoblinShaman
  - GoblinBrute
  - GoblinShaman
  - GoblinBrute
  - GoblinShaman
  - GoblinBrute
  - GoblinShaman
  - GoblinBrute
  # Rare elite spawns for excitement (35% chance)
  - GoblinBrute
  - Lox
  - GoblinBrute
  - Lox
  - GoblinBrute
  - Lox
  - GoblinBrute
  - Lox

PlainsCreatures3:
  # Elite locations - Maximum challenge and rewards
  # Focus: Ultimate materials and rare drops for endgame progression
  # Maximum elite density for premium rewards
  - Goblin
  - Goblin
  - GoblinShaman
  - GoblinShaman
  - GoblinBrute
  - GoblinBrute
  # Elite variants for ultimate materials (75% chance)
  - GoblinShaman
  - GoblinBrute
  - GoblinShaman
  - GoblinBrute
  - GoblinShaman
  - GoblinBrute
  - GoblinShaman
  - GoblinBrute
  - GoblinShaman
  - GoblinBrute
  - GoblinShaman
  - GoblinBrute
  - GoblinShaman
  - GoblinBrute
  - GoblinShaman
  - GoblinBrute
  - GoblinShaman
  - GoblinBrute
  - GoblinShaman
  - GoblinBrute
  - GoblinShaman
  - GoblinBrute
  - GoblinShaman
  - GoblinBrute
  # Rare elite spawns for maximum excitement (35% chance)
  - GoblinBrute
  - Lox
  - GoblinBrute
  - Lox
  - GoblinBrute
  - Lox
  - GoblinBrute
  - Lox
  - GoblinBrute
  - Lox
  - GoblinBrute
  - Lox

# Swamp Pack 1 - Enhanced Creature Variety
# Combined into SwampCreatures_Standard

# Mistlands Pack 1 - Enhanced Creature Variety
# Combined into MistlandsCreatures_Full and MistlandsCreatures_Light

# Ashlands Pack 1 - Enhanced Creature Variety
# Thematic consistency with Ashlands biome identity
# Performance optimized with enhanced elite density
# to compensate for reduced spawn quantities

AshlandsCreatures1:
  # Common ashlands locations - Diverse mix for early Ashlands progression
  # Focus: Reliable material farming with moderate challenge
  # Enhanced variety to compensate for reduced spawn quantities
  - Morgen
  - Charred_Warrior
  - Charred_Archer
  - Morgen
  - Charred_Warrior
  - Charred_Archer
  - Morgen
  - Charred_Warrior
  - Charred_Archer
  - Morgen
  # Elite variants for better materials (40% chance)
  - Charred_Warrior
  - Charred_Archer
  - Charred_Mage
  - Charred_Warrior
  - Charred_Archer
  - Charred_Mage
  - Charred_Warrior
  - Charred_Archer
  # Rare spawns for excitement (30% chance)
  - Charred_Mage
  - Morgen_NonSleeping
  - Charred_Mage
  - Morgen_NonSleeping
  - Charred_Mage
  - Morgen_NonSleeping

# Adventure Map Pack 1 - Enhanced Creature Variety
# Combined into MistlandsCreatures_Full and MountainsCreatures_Standard
