name: LanceDvergr_TW
m_weight: 3.5
m_name: <color=#D4AF37>$lance_dvergr_TW</color>
m_description: $lance_dvergr_description_TW
clonePrefabName: 
mockName: 
customIcon: 
material: 
materials: 
customVisual: 
snapshotRotation: 
snapshotOnMaterialChange: true
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack:
  AttackType: Horizontal
  Attack_Animation: spear_throw
  Attack_Random_Animation: 0
  Chain_Attacks: 1
  Hit_Terrain: true
  Hit_Friendly: false
  Custom_AttackSpeed: 1
  m_attackStamina: 20
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.4
  Attack_Start_Noise: 15
  Attack_Hit_Noise: 30
  Dmg_Multiplier_Per_Missing_Health: 0
  Damage_Multiplier_By_Health_Deficit_Percent: 0
  Stamina_Return_Per_Missing_HP: 0
  DmgMultiplier: 1
  ForceMultiplier: 1.5
  StaggerMultiplier: 2
  RecoilMultiplier: 0
  SelfDamage: 0
  Attack_Kills_Self: false
  AttackRange: 3.5
  AttackHeight: 2
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 
  ReloadTimeMultiplier: 1
  Reload_Stamina_Drain: 0
  Reload_Eitr_Drain: 
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 90
  Attack_Ray_Width: 0
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Reset_Chain_If_hit: None
  SpawnOnHit: 
  SpawnOnHit_Chance: 0
  Attack_status_effect: 
  Attack_status_effect_chance: 
  Raise_Skill_Amount: 1
  Skill_Hit_Type: Character
  Special_Hit_Skill: None
  Special_Hit_Type: None
  Attack_Projectile: 
  Projectile_Vel: 10
  Projectile_Accuraccy: 0
  Projectiles: 1
  Skill_Accuracy: false
  Launch_Angle: 0
  Projectile_Burst: 1
  Burst_Interval: 0
  Destroy_Previous_Projectile: false
  PerBurst_Resource_usage: false
  Looping_Attack: false
  Consume_Item: false
  AEffects: 
  AEffectsPLUS:
    Hit_Effects: []
    Hit_Terrain_Effects: []
    Start_Effect: []
    Trigger_Effect: []
    Trail_Effect: []
    Burst_Effect: []
Secondary_Attack:
  AttackType: Projectile
  Attack_Animation: spear_throw
  Attack_Random_Animation: 0
  Chain_Attacks: 0
  Hit_Terrain: true
  Hit_Friendly: false
  Custom_AttackSpeed: 1
  m_attackStamina: 30
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.6
  Attack_Start_Noise: 20
  Attack_Hit_Noise: 35
  Dmg_Multiplier_Per_Missing_Health: 0
  Damage_Multiplier_By_Health_Deficit_Percent: 0
  Stamina_Return_Per_Missing_HP: 0
  DmgMultiplier: 1.8
  ForceMultiplier: 2
  StaggerMultiplier: 3
  RecoilMultiplier: 0
  SelfDamage: 0
  Attack_Kills_Self: false
  AttackRange: 1
  AttackHeight: 1.5
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 
  ReloadTimeMultiplier: 1
  Reload_Stamina_Drain: 0
  Reload_Eitr_Drain: 
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 90
  Attack_Ray_Width: 0
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Reset_Chain_If_hit: None
  SpawnOnHit: 
  SpawnOnHit_Chance: 0
  Attack_status_effect: 
  Attack_status_effect_chance: 
  Raise_Skill_Amount: 1
  Skill_Hit_Type: Character
  Special_Hit_Skill: None
  Special_Hit_Type: None
  Attack_Projectile: SpearDvergr_TW_projectile
  Projectile_Vel: 60
  Projectile_Accuraccy: 1
  Projectiles: 1
  Skill_Accuracy: false
  Launch_Angle: 0
  Projectile_Burst: 1
  Burst_Interval: 0
  Destroy_Previous_Projectile: false
  PerBurst_Resource_usage: false
  Looping_Attack: false
  Consume_Item: false
  AEffects: 
  AEffectsPLUS:
    Hit_Effects: []
    Hit_Terrain_Effects: []
    Start_Effect: []
    Trigger_Effect: []
    Trail_Effect: []
    Burst_Effect: []
Damage:
  Blunt: 0
  Chop: 0
  Damage: 0
  Fire: 0
  Frost: 0
  Lightning: 0
  Pickaxe: 0
  Pierce: 110
  Poison: 0
  Slash: 0
  Spirit: 40
Damage_Per_Level:
  Blunt: 0
  Chop: 0
  Damage: 0
  Fire: 0
  Frost: 0
  Lightning: 0
  Pickaxe: 0
  Pierce: 7
  Poison: 0
  Slash: 0
  Spirit: 3
Armor:
  armor: 0
  armorPerLevel: 0
FoodStats: 
Moddifiers:
  m_movementModifier: -0.06
  m_EitrRegen: 0
  m_homeItemsStaminaModifier: 0
  m_heatResistanceModifier: 0
  m_jumpStaminaModifier: 0
  m_attackStaminaModifier: 0
  m_blockStaminaModifier: 0
  m_dodgeStaminaModifier: 0
  m_swimStaminaModifier: 0
  m_sneakStaminaModifier: 0
  m_runStaminaModifier: 0
SE_Equip: 
SE_SET_Equip: 
ShieldStats:
  m_blockPower: 18
  m_blockPowerPerLevel: 2
  m_timedBlockBonus: 2.5
  m_deflectionForce: 40
  m_deflectionForcePerLevel: 5
m_maxStackSize: 1
m_canBeReparied: true
m_destroyBroken: false
m_dodgeable: true
Attack_status_effect: 
Attack_status_effect_chance: 1
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 5
m_knockback: 40
m_useDurability: true
m_useDurabilityDrain: 1
m_durabilityDrain: 0
m_maxDurability: 180
m_durabilityPerLevel: 60
m_equipDuration: 0.4
Attach_Override: None
m_skillType: Spears
m_animationState: Atgeir
m_itemType: TwoHandedWeapon
m_toolTier: 6
m_maxQuality: 4
m_value: 0
ConsumableStatusEffect: 
AppendToolTip: \n<color=#4682b4>Depths of Dvergr Mastery</color>\n<color=#888888>A ceremonial lance of the deep craftsmen.\nCannot be crafted - only claimed from the Queen's domain.\n<i>(5% drop chance from Queen)</i></color>
damageModifiers: []
GEffects: 
GEffectsPLUS:
  Hit_Effects: []
  Hit_Terrain_Effects: []
  Start_Effect: []
  Hold_Start_Effects: []
  Trigger_Effect:
  - name: fx_swing_camshake
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  - name: sfx_spear_hit
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  Trail_Effect: []
