name: DualAxeDemonic_TW
m_weight: 2.8
m_name: "<color=#D4AF37>Demonic Dual Axes</color>"
m_description: Twin axes forged in the depths of darkness.
clonePrefabName: 
mockName: 
customIcon: 
material: 
materials: 
customVisual: 
snapshotRotation: 
snapshotOnMaterialChange: true
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack:
  AttackType: Horizontal
  Attack_Animation: battleaxe_attack
  Attack_Random_Animation: 0
  Chain_Attacks: 2
  Hit_Terrain: true
  Hit_Friendly: false
  Custom_AttackSpeed: 1
  m_attackStamina: 15
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.3
  Attack_Start_Noise: 15
  Attack_Hit_Noise: 30
  Dmg_Multiplier_Per_Missing_Health: 0
  Damage_Multiplier_By_Health_Deficit_Percent: 0
  Stamina_Return_Per_Missing_HP: 0
  DmgMultiplier: 1
  ForceMultiplier: 1.2
  StaggerMultiplier: 1.5
  RecoilMultiplier: 0
  SelfDamage: 0
  Attack_Kills_Self: false
  AttackRange: 2.2
  AttackHeight: 1.6
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 
  ReloadTimeMultiplier: 1
  Reload_Stamina_Drain: 0
  Reload_Eitr_Drain: 
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 90
  Attack_Ray_Width: 0
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Reset_Chain_If_hit: None
  SpawnOnHit: 
  SpawnOnHit_Chance: 0
  Attack_status_effect: 
  Attack_status_effect_chance: 
  Raise_Skill_Amount: 1
  Skill_Hit_Type: Character
  Special_Hit_Skill: None
  Special_Hit_Type: None
  Attack_Projectile: 
  Projectile_Vel: 10
  Projectile_Accuraccy: 0
  Projectiles: 1
  Skill_Accuracy: false
  Launch_Angle: 0
  Projectile_Burst: 1
  Burst_Interval: 0
  Destroy_Previous_Projectile: false
  PerBurst_Resource_usage: false
  Looping_Attack: false
  Consume_Item: false
  AEffects: 
  AEffectsPLUS:
    Hit_Effects: []
    Hit_Terrain_Effects: []
    Start_Effect: []
    Trigger_Effect: []
    Trail_Effect: []
    Burst_Effect: []
Secondary_Attack:
  AttackType: Horizontal
  Attack_Animation: battleaxe_combo
  Attack_Random_Animation: 0
  Chain_Attacks: 1
  Hit_Terrain: true
  Hit_Friendly: false
  Custom_AttackSpeed: 1
  m_attackStamina: 22
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.4
  Attack_Start_Noise: 20
  Attack_Hit_Noise: 35
  Dmg_Multiplier_Per_Missing_Health: 0
  Damage_Multiplier_By_Health_Deficit_Percent: 0
  Stamina_Return_Per_Missing_HP: 0
  DmgMultiplier: 1.4
  ForceMultiplier: 1.8
  StaggerMultiplier: 2
  RecoilMultiplier: 0
  SelfDamage: 0
  Attack_Kills_Self: false
  AttackRange: 2.5
  AttackHeight: 1.8
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 
  ReloadTimeMultiplier: 1
  Reload_Stamina_Drain: 0
  Reload_Eitr_Drain: 
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 90
  Attack_Ray_Width: 0
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Reset_Chain_If_hit: None
  SpawnOnHit: 
  SpawnOnHit_Chance: 0
  Attack_status_effect: 
  Attack_status_effect_chance: 
  Raise_Skill_Amount: 1
  Skill_Hit_Type: Character
  Special_Hit_Skill: None
  Special_Hit_Type: None
  Attack_Projectile: 
  Projectile_Vel: 10
  Projectile_Accuraccy: 0
  Projectiles: 1
  Skill_Accuracy: false
  Launch_Angle: 0
  Projectile_Burst: 1
  Burst_Interval: 0
  Destroy_Previous_Projectile: false
  PerBurst_Resource_usage: false
  Looping_Attack: false
  Consume_Item: false
  AEffects: 
  AEffectsPLUS:
    Hit_Effects: []
    Hit_Terrain_Effects: []
    Start_Effect: []
    Trigger_Effect: []
    Trail_Effect: []
    Burst_Effect: []
Damage:
  Blunt: 0
  Chop: 20
  Damage: 0
  Fire: 0
  Frost: 0
  Lightning: 0
  Pickaxe: 0
  Pierce: 0
  Poison: 0
  Slash: 50
  Spirit: 25
Damage_Per_Level:
  Blunt: 0
  Chop: 2
  Damage: 0
  Fire: 0
  Frost: 0
  Lightning: 0
  Pickaxe: 0
  Pierce: 0
  Poison: 0
  Slash: 3
  Spirit: 2
Armor:
  armor: 0
  armorPerLevel: 0
FoodStats: 
Moddifiers:
  m_movementModifier: -0.04
  m_EitrRegen: 0
  m_homeItemsStaminaModifier: 0
  m_heatResistanceModifier: 0
  m_jumpStaminaModifier: 0
  m_attackStaminaModifier: 0
  m_blockStaminaModifier: 0
  m_dodgeStaminaModifier: 0
  m_swimStaminaModifier: 0
  m_sneakStaminaModifier: 0
  m_runStaminaModifier: 0
SE_Equip: 
SE_SET_Equip: 
ShieldStats:
  m_blockPower: 12
  m_blockPowerPerLevel: 1
  m_timedBlockBonus: 1.8
  m_deflectionForce: 25
  m_deflectionForcePerLevel: 2
m_maxStackSize: 1
m_canBeReparied: true
m_destroyBroken: false
m_dodgeable: true
Attack_status_effect: 
Attack_status_effect_chance: 1
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 3
m_knockback: 30
m_useDurability: true
m_useDurabilityDrain: 1
m_durabilityDrain: 0
m_maxDurability: 150
m_durabilityPerLevel: 40
m_equipDuration: 0.25
Attach_Override: None
m_skillType: Axes
m_animationState: OneHanded
m_itemType: OneHandedWeapon
m_toolTier: 3
m_maxQuality: 4
m_value: 0
ConsumableStatusEffect: 
AppendToolTip: "\n<color=#8b0000> Svalt's Demonic Fury </color>\n<color=#888888>Twin axes forged in the depths of darkness.\nCannot be crafted - only torn from the demon's grasp.\n<i>(5% drop chance from Svalt)</i></color>"
damageModifiers: []
GEffects: 
GEffectsPLUS:
  Hit_Effects: []
  Hit_Terrain_Effects: []
  Start_Effect: []
  Hold_Start_Effects: []
  Trigger_Effect:
  - name: fx_swing_camshake
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  - name: sfx_axe_hit
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  Trail_Effect: []
