name: BMB_LightningBow
m_name: <color=#D4AF37>$bmb_lightningbow_name</color>
AppendToolTip: \n<color=#696969>Stormforged Arc</color>\n<color=#888888>Cannot be crafted — earned as a rare trophy.\n<i>(3% drop chance from Storm Herald, 2 items)</i></color>

